name = "abedderworld-redirects"
compatibility_date = "2024-01-01"

# Pages configuration
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "REDIRECTS"
id = "f4695384362148309e43b8455ef1379d"